services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    env_file: ./apps/api/.env
    restart: unless-stopped
    ports:
      - 3000
    mem_limit: 2g
    memswap_limit: -1
    mem_swappiness: 20

  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    env_file: ./apps/client/.env.local
    depends_on:
      - 'api'
    restart: unless-stopped
    ports:
      - 3000
  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    env_file: ./apps/admin/.env.local
    depends_on:
      - 'api'
    restart: unless-stopped
    ports:
      - 3000
